templates_dir: templates/xbeach_holland_default
output_dir: test_cli_output
variable_parameters:
  var1:
    - 225
    - 226
  var2:
    - 514
    - 315
fixed_parameters: {}
cases_name_format: "holland_{{ var1 }}_{{ var2 }}"
mode: all_combinations
command: "pwd; sleep 10; echo 'Using custom launcher with {{ var1 }}'"
#num_workers: 1
